{{- if .Values.knativeServing.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.knativeServing.namespace }}
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
