apiVersion: v2
name: cluster-serverless
description: GitOps-Powered Serverless Platform for VPS/Homelab
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
- name: serverless-infra
  version: "1.0.0"
  condition: serverless-infra.enabled
- name: serverless-app
  version: "1.0.0"
  condition: serverless-app.enabled

keywords:
  - kubernetes
  - serverless
  - knative
  - gitops
  - argocd
maintainers:
  - name: BenedictusAryo
home: https://github.com/BenedictusAryo/cluster-serverless
sources:
  - https://github.com/BenedictusAryo/cluster-serverless