---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wa-notif-postgres-admin
  namespace: apps
spec:
  encryptedData:
    postgres-password: AgBsxYP16j6xuT1TkGoKKLrqGNv8n76eTko/nPW76Gb8gTWUAPPDmdR40hMzHc81zBJww5F2N42UfrEWAIDSBkSyw5hOkWmfgdDTqbRDtt/kpLvg2apIFu4rnqb0EdmBCv7seE0Q4/un3RJ7VtQUBlsYSBCykH/nEw/wKEehiKwOLhoRNyNerDAinIeEP83mM9pPhKY2BfGmu1BgXw7cQaGEV/pAJYNL9gvS1lAetJm2EGcatlB0X3E8IZFVco8EYzYaGlabDjKcpuiINFUk74MjVmwgp3AQ8r+6WuVbBMSMW167WiPmgVZxoQXpwefBBzPXk4E/606SJ3LEEQcIQgSQDBBgt2K6kAP3IF/05tmpGMJyBiRegAc4pXpONGb1GrgaOYb2RWYGOwo4UHmz/H7wytymq0W/SownhqkNwZdETukUsvLy6I6v54cJ5Uy+5Btsuq0W4TMsgASyJbtEF7lzuZHWRWjDAMSGPVovzKA/+ZxOz9Qjl0MK7vuwat64wRx0/7UNKqWGPq+h0gPALIJODKUxV5bjHAqkDrSc8I2eI4m04vonbq8bHBTkP/QxZ6/JIrD192VxMj9CurjBhDgt48YuFtBbK9EAabzJ50aJ3bWZ/8RJDwoHT2uMHujVVAkT9m/2ZVI0NKaCkoTz8SIw/qMFMq8FOSXj7LYJFuaZlf+mAUZ8xqcpwQ1jE2Vt90awWWz49/onPcktVw==
  template:
    metadata:
      name: wa-notif-postgres-admin
      namespace: apps
