apiVersion: v1
kind: Secret
metadata:
  name: matius-booking-secrets
  namespace: apps
type: Opaque
data:
  # User to provide base64 encoded values
  secret-key: "<USER_TO_PROVIDE_BASE64_SECRET_KEY>"
  # format: postgresql://username:password@postgres.infra.svc.cluster.local:5432/matius_booking
  database-url: "<USER_TO_PROVIDE_BASE64_DATABASE_URL>"
