apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: matius-booking
  namespace: apps
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/min-scale: "1"
        redeploy-timestamp: "2026-03-05T00:00:05Z"

    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - image: ghcr.io/benedictusaryo/aplikasipeminjamanruang_parokibintaro:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: matius-booking-secrets
                  key: secret-key
            - name: DEBUG
              value: "True" # Set to True for testing visibility
            - name: ALLOWED_HOSTS
              value: "*"
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.prod"
            - name: DATABASE_URL
              value: "sqlite:////app/db.sqlite3"
            - name: DB_ENGINE
              value: "django.db.backends.sqlite3"
            - name: BASE_URL
              value: "http://matius.benedict-aryo.com"
            - name: PYTHONUNBUFFERED
              value: "1"
