apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pdf-utils-secrets
  namespace: apps
spec:
  encryptedData:
    PLACEHOLDER: AgAraK+0ZqCKu8Atsgc75pffbxAxGvmPrgWoE9d3PC2M0RhokSui0ciM5nynaYZGcXzeFNk92Ttju3MTWMYhqfUm2K52mX3gNVkUkx4RlwCJfYMwI9AohXzfsvzYa7a3o2EeVuc/opsCM9EkcBl49f6oj50D4AKq/qEa3Cfr1AfeKW5gACf7x6OKFaCG+Q3roC1mD2KSyiYAKqEmhVz/vU6UGDr7gQB1cZN4IXe1sCAvFmryYTbCcgWSUSDaqaTOirmMCOVdtzrECkYufkfryj09UK0GHij3oC9ylIlV3Ubcl1OeXvN2ZK7M4BtspJtSVq+FDtBI/1xH1JconhEbhDd/p/3W3Z1zdelwY5hMD3EnITx2E5xzfsgCtdFSu8fcLw46xeCTwKg8dPiCvCyPU48dPkZ9hiG7BahmZalpUpGs0p5it859zukTdVqovQTk+/2TaGiOqHJwvfM6EdqY+jufHRZF+ivbMgADNISdfPbS+4kNVGhWP8ZcaBHGGZNHHNiCk5roGePcU19cvSulPQgJAbUQ3pFs4srNK7+9dvYCNZQjURMF5pkywVmkrYLanlDrcfrbnpwvYZl2YAHUJqjXclHnU+gEwT2ISxlWpnvGqW+sx/FT9UmIAMRjHWKaAhiAd4LmVbgM/rG+2TQyAj2ZQ+VoO17bdXEPc/+mcU2OCzoD8tdi/JeWCRw3SFoQDDM=
