apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin
  namespace: infra
spec:
  encryptedData:
    postgres-password: AgAfMWZeQMF9Vd3Lvc/ro7KhQlNJCcmFC/LigBSAlu7Si63O96bf5eCRX06Zpevv8E3DqGim3M7x658Ry4XZOiRht1/BX9WsZHLY+6hCSFWWiZFrvGznCch09BM7mkvtQ708/DCtZgN3hHJRcX2EzjbyqxQt0u+64yDjdp0bGdrFGY2+i5M79C2+RZpLjKGuR9+0Zfst4Vk+ZhWV79mD5+UBIwqaTzL7tOePow9k8jwMJC+QSdxe1SiI0FBwExIl8bnmNLwe0K011j3U6rKpr6xIvqMEKmxsPBwY/OwAOjFAk8iASV5KpU/nvxopg/GYcKK+VFx+LP1vFQaVLQc9EIobWvywMrQLlk25SqvDmQrirljAzB2qf+GJN22FN/w7TXCw90WnLRNZHBX+XH8H0GT27voYTehX/MuVnNsxAbIuX1zYsfyYYYQdYyHzxCfi/18+4RBjZDTIkmUxBMLJNdfzFEl6gQSoNe4TiBxlKJ/SIQmmE/r1gM4zA8dj81rss5iiKdsIh7FxFqlTxwHuxBwHQZ5EfVDMYFHHUDSUNsjkebPWOQvrJOAqqRK5rwn1pFy19NG4PhGMIt/nyOwLxmrLa5zeXVL1BO4Matm4zl5xlIHkx+1kL12pv7sjTabQSXOEiZTyaFd9mgQzH0HPiZAgAXreq0bJu06VeIlZ9g5wcQx6iIGKAUH9b+Y4bQPPvc6M+osYcB0XG1xFDQ==
  template:
    metadata:
      name: postgres-admin
      namespace: infra
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.16
    helm:
      releaseName: postgres
      values: |
        fullnameOverride: postgres
        image:
          repository: bitnamilegacy/postgresql
          tag: "17"
        auth:
          existingSecret: postgres-admin
          username: postgres
        primary:
          service:
            ports:
              postgresql: 5432
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
