# Dependencies for cluster-serverless Helm chart
# This file lists external dependencies that may be required for the chart

dependencies:
  # Cilium CNI - Container Network Interface
  - name: cilium
    description: "eBPF-based Networking, Observability, and Security"
    repository: https://helm.cilium.io/
    version: "1.14.5"
    optional: false
    
  # Knative Serving - Serverless workload execution
  - name: knative-serving
    description: "Kubernetes-based platform to deploy and manage serverless workloads"
    repository: https://knative.dev/docs/install/
    version: "1.11.0"
    optional: false
    
  # Knative Eventing - Event-driven architecture
  - name: knative-eventing
    description: "Event-driven architecture components for Kubernetes"
    repository: https://knative.dev/docs/install/
    version: "1.11.0"
    optional: false
    
  # Kourier - Knative ingress controller
  - name: kourier
    description: "Lightweight Knative Serving ingress"
    repository: https://github.com/knative-extensions/net-kourier
    version: "1.11.0"
    optional: false
    
  # OpenTelemetry - Observability framework
  - name: opentelemetry-collector
    description: "Vendor-agnostic way to receive, process and export telemetry data"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: "0.74.0"
    optional: true
    
  # Jaeger - Distributed tracing platform
  - name: jaeger
    description: "End-to-end distributed tracing and monitoring"
    repository: https://jaegertracing.github.io/helm-charts
    version: "0.71.0"
    optional: true
    
  # Cloudflare Tunnel - Secure tunnel to expose services
  - name: cloudflare-tunnel
    description: "Securely expose services without opening firewall ports"
    repository: https://github.com/cloudflare/cloudflared
    version: "latest"
    optional: true

notes: |
  This chart orchestrates multiple components to create a complete serverless Kubernetes platform:
  
  1. Cilium provides advanced networking, security, and observability
  2. Knative Serving enables serverless workload execution
  3. Knative Eventing provides event-driven architecture capabilities
  4. Kourier serves as a lightweight ingress controller for Knative
  5. OpenTelemetry and Jaeger provide comprehensive observability and tracing
  6. Cloudflare Tunnel enables secure external access to services
  
  For detailed installation instructions, refer to the README.md file.
