{{- if .Values.cloudflareTunnel.enabled }}
{{- if not .Values.cloudflareTunnel.credentials.useExistingSecret }}
# NOTE: This is a SealedSecret - the encrypted tunnel token
# To create/update:
# 1. Get tunnel token from Cloudflare Zero Trust dashboard
# 2. Create sealed secret:
#    echo -n 'YOUR_TOKEN' | kubectl create secret generic cloudflare-tunnel-secret \
#      --dry-run=client -o yaml --from-file=tunnel-token=/dev/stdin \
#      -n cloudflare-tunnel | \
#    kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system \
#      -o yaml > infra/templates/cloudflare-tunnel/secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.cloudflareTunnel.credentials.secretName }}
  namespace: {{ .Values.cloudflareTunnel.namespace }}
spec:
  encryptedData:
    tunnel-token: AgCGV41ZfnaRXqoUxRkSLsSREh2oK+JMmJHaZnAAoJSiJVIvkKzJnp766wJQ7n+AJZEUebNEN3AMs/5TqZA28bogQsxaw6kUR9aisVuN07G5E8Lvqrcoo255SFZ3vnr9kugj9iViCK4WOxn/niCNIuHjWF/KKaHAy312/n3B9lrLtkV+RT3dVZA4NKfGyo/nivGTXOtKJxXYrsvavu38B/r7olPuuugFs42JR4TOfsg6SGRXCUp+TzcWB7pkBSrY2ctpAYYiVo/gvXjpe2W0MeYeuAQn5joWIY3NXl3Uxfg7B6OYl1/Fxa8WJrAs03FRMe8z13laswjgKMbFSm9LsEVLa/Nl9V6y8+1CHaztM3A7sE28hGATiuUka9fKQE6+8222uo2Ttgktxmejj3CBDalw2yYlg0mkVbZOA99BHD9gYcTY3sbk+c4TL30wAuzRFZMLOuXVAUmAWiSN+NWyZ2M5mzgCs2Xx+TiEnqMujcR+gFR0u2PmiFNh/j/ZEkkSF/4Q+Tq33Pu4qfyKe4PwG8RYTLQWjTy7EErl+jhQyQSEHQUCFt906cDwEae0zSFKtPpY184tqs2y4QLouO7K3NOO7lNsVgQpSiXy9XINFA6jJVNZGQEgFDqe1vgJeBCeGG8FiIUFk8BJhvUX7jOWNnMewSdaLf8BRz4P56pzDiO9hE/n4jZ4FWuUasM6CALGESX9blQ69E2SE/iqsDHIrqIkMNMrgrj1Z+4iFKPODvOsWZJ8cx06xPv+d4BSKNozACg76jzEF+ATJnWd+fM4LqtYBFSplT84KloIOJH+aR0RMxXwzoKFXBFltUwX+hkQeKM91qGmJKOZCq1KV1PI7/jdRecLbVpzwlrDYFje5SReJ4zP5zGEqrEl56K0FuoiGEwRUwE8AeE4tQiKm8VlzQ0f56EkMM6ozZpYq7lWibttk4JhABk/javk
  template:
    metadata:
      name: {{ .Values.cloudflareTunnel.credentials.secretName }}
      namespace: {{ .Values.cloudflareTunnel.namespace }}
{{- end }}
{{- end }}
