{{- if .Values.cloudflareTunnel.enabled }}
{{- if .Values.cloudflareTunnel.tunnelToken }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: {{ .Values.cloudflareTunnel.namespace }}
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  token: {{ .Values.cloudflareTunnel.tunnelToken }}
{{- end }}
{{- end }}
