# Cloudflare Tunnel Sealed Secret
# Generated on: Mon Nov 17 03:36:03 AM UTC 2025
# 
# This secret is encrypted with the cluster's Sealed Secrets public key
# and can only be decrypted by the sealed-secrets-controller in the cluster.
# 
# To regenerate: run scripts/generate-sealed-secret.sh
{{- if .Values.cloudflareTunnel.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgBawAu5iK7unEjJHuWc/r7TGm9WXUbMCROkMZE28/ITtm8fp6RljqvqCg5U4aErpswMmIzMQwj/gQlG/D7FRcEo6kaEko8ftWpkgqrOVrYUdSoEm97tb43ujSWkMpR/BpdQMqEpHpK5Z9ncVEQ6CpfLZg7SNBoqVQHIe9SzXgJdry+7qezROZHgIgKGoYBFqsnaOpzVG4hQV3T5i9VQRwuFhTgE9KskdJItm3Rtx3r5vXkCeekYthX83M5JkVu7I2j4A91vcSax4RbKbuFl+Eo8orEbGavdHMTBS5YzxU0Xz2zRGphLfysKKvrdgu26JaTQOlyu41LUsWYZJzE+rGgOD5kGXy5NiLsyJ+kOX/WdNDcRwwaRT8l9v45SD4QkLag7vS93j3t+6N/FiiYN8VwMnAgS8Q6sQsoNhWFTDEdVIhAlVE/7HeoElmAL2ZA7PYIPLAvh2npGGmM4wGXNnLm8p4yyfrIqcfAjAcc1O7yvaGsCTpV68tM9DamsKLGmJoQOFGAoPuYZzcbahBcMuG/e1RcfolktZzbdEJsH9Te7WylGfNfFepIKRZYWDcNDJQfQITge9AOAO4SH5DHBF36Q9GLmAlPqKrcj6WEomoClEdlju3F/STjOz+xaEdBTIS8qTlk7PEs+V29oniu0t0IY82vSxl2i11zjUiqD0a0neqkdAMaxAAcP1yeXtFrleavo09TSQq9VZd6z8QTkBcBpCxpBJFu9iy5vHCugGBtw5pqrwkjMbpFJGarVfAsf+jQPS93FeWQqylIaOthHErAsubCEcub6SjgX3Cm2r/KmD5fAtQv6uf4g/8TONCaLqNVeGclk6Ro53qaf2Nuaxu0CXh0uxRfIOvO0We+fyT7qVEzMYaS3DE4XBOqY+HqwfA1N0w0P3oikKFndUjgMovyxX9/zZ8MRxzq3sclXzeadAOYwhutRVqn+
  template:
    metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflare-tunnel
    type: Opaque
{{- end }}
