{{- if .Values.cloudflareTunnel.enabled }}
{{- if not .Values.cloudflareTunnel.credentials.useExistingSecret }}
# NOTE: This is a SealedSecret - the encrypted tunnel token
# To create/update:
# 1. Get tunnel token from Cloudflare Zero Trust dashboard
# 2. Create sealed secret:
#    echo -n 'YOUR_TOKEN' | kubectl create secret generic cloudflare-tunnel-secret \
#      --dry-run=client -o yaml --from-file=tunnel-token=/dev/stdin \
#      -n cloudflare-tunnel | \
#    kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system \
#      -o yaml > infra/templates/cloudflare-tunnel/secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.cloudflareTunnel.credentials.secretName }}
  namespace: {{ .Values.cloudflareTunnel.namespace }}
spec:
  encryptedData:
    tunnel-token: AgAZR3eyo+utfXKD5RdV01Gk0Cn26I5fQq/M2GHokEXzLDJ4rcvlUsNPUtbm3Fl9qLBrUGh2+P/MtV8LJ9jRvZLxZYigG8wc+lmHjK/MiiXleIJeBEGbrbbFUDyrf5jm6DhM1PYT4iMiorZGU8QlDuLhtTT1kWW8mbp5roCVPiGJJOzxpK+HB41mRXoy7/oiNHU4Vyxk4bVxj6dNklvG+STLSWVCfdTQqw2oRRcKAJF4WBWOdJ1G9LlIJ/Ef+wnP001fQ7PpoPiQzC+zRFMx+HDRAPIcBpw+BoLdEwlLvqYoEAkhFeTlN1NAaZPWwMgFL23OSWLTB3/0EEsR++tACTMiQ3MIk1+9BcnQg+n4tcHXlqX84kL/8Ydfj1DAVozksQQxDwI9TSPuE2qkL5NM5ISpbvz/69jP9vc4YyhBUmZJ5FaB5HV3p1bZGux1zsOMad9Mh4AHOB6rZYT/mmSSGSZpjkVBazO3Uos4x8cpI7psGUj59/1XubS2bABhlzFzxX/GxrYb6TKW0av6loUYMe7lqgo95D98gedPYxSCqAjcAd+XDD67kofm2gJwkzLMYg9laqktVRT6PSo3ZO98YCpstIuoGQb6oFO+z5+pg2SyOorbjgDjwVUc98Lcyg4sA7jt69ud9SyBNHtjXpnNDxCw/b1aFKPEn6PXrL5d6ob+L4YjIgiYdAvh+a+E/hCJ5+wf6Yyxmf4FRnYJ2Kfq6zAj/CXt+X1ZRmU6RRu6K3HLD8dTWnTVRNwpm9GG6uACJbP0MmhzIxrBYqX+w8Xu9L8KnaFNP9YlSxdAe3SSunUeWPR9OlbtrdHwhr/7XTPqTGAblHu8K7aCJJA0Oli5jXaYKB2UVuptdJo1T0orULjQn2tNFNDrFYnF0i+laFTI7l+XYwGyzwJsy9Foe/xBTrTjvVOmg7jSBT+a5xVXqKdSRLc145A7UJm6
  template:
    metadata:
      name: {{ .Values.cloudflareTunnel.credentials.secretName }}
      namespace: {{ .Values.cloudflareTunnel.namespace }}
{{- end }}
{{- end }}
