{{- if .Values.configMap }}
{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default (printf "%s-config" .Values.service.name) }}
  namespace: {{ .Values.service.namespace }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- end }}

{{- if .Values.secret }}
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (printf "%s-secrets" .Values.service.name) }}
  namespace: {{ .Values.service.namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- if .Values.service.annotations }}
        {{- range $key, $value := .Values.service.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      containers:
      - image: {{ .Values.service.image }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        {{- range .Values.service.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.service.envFromConfigMap }}
        envFrom:
        - configMapRef:
            name: {{ .Values.service.envFromConfigMap }}
        {{- end }}
        {{- if .Values.service.envFromSecret }}
        - secretRef:
            name: {{ .Values.service.envFromSecret }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.service.resources.requests.memory | default "64Mi" | quote }}
            cpu: {{ .Values.service.resources.requests.cpu | default "250m" | quote }}
          limits:
            memory: {{ .Values.service.resources.limits.memory | default "128Mi" | quote }}
            cpu: {{ .Values.service.resources.limits.cpu | default "500m" | quote }}
        {{- if .Values.service.volumeMounts }}
        volumeMounts:
        {{- range .Values.service.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- if .Values.service.volumes }}
      volumes:
      {{- range .Values.service.volumes }}
      - name: {{ .name }}
        {{- if .configMap }}
        configMap:
          name: {{ .configMap.name }}
          {{- if .configMap.items }}
          items:
          {{- range .configMap.items }}
          - key: {{ .key }}
            path: {{ .path }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if .secret }}
        secret:
          secretName: {{ .secret.secretName }}
          {{- if .secret.items }}
          items:
          {{- range .secret.items }}
          - key: {{ .key }}
            path: {{ .path }}
          {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
