{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.jaeger.namespace }}
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
