{{- if .Values.cilium.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: {{ .Values.cilium.version }}
    helm:
      releaseName: cilium
      values: |
        kubeProxyReplacement: {{ .Values.cilium.kubeProxyReplacement }}
        k8sServiceHost: localhost
        k8sServicePort: 6443
        operator:
          replicas: 1
        hubble:
          enabled: {{ .Values.cilium.hubble.enabled }}
          relay:
            enabled: {{ .Values.cilium.hubble.relay.enabled }}
          ui:
            enabled: {{ .Values.cilium.hubble.ui.enabled }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data
{{- end }}
