{{- if .Values.knativeServing.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: knative-serving-install
  namespace: argocd
data:
  install.sh: |
    #!/bin/bash
    kubectl apply -f https://github.com/knative/serving/releases/download/knative-v{{ .Values.knativeServing.version }}/serving-crds.yaml
    kubectl apply -f https://github.com/knative/serving/releases/download/knative-v{{ .Values.knativeServing.version }}/serving-core.yaml
{{- end }}
