{{- if .Values.knativeEventing.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-eventing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/knative/eventing
    targetRevision: knative-v{{ .Values.knativeEventing.version }}
    path: config/core
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-eventing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
